THEMES = {
    "Ocean Blue": {
        "primary": "#1D4ED8",
        "secondary": "#0F172A",
        "accent": "#E0E7FF",
        "text": "#111827",
        "muted": "#6B7280",
        "bg": "#F8FAFC",
        "card": "#FFFFFF",
        "border": "#CBD5E1",
    },
    "Emerald": {
        "primary": "#059669",
        "secondary": "#064E3B",
        "accent": "#D1FAE5",
        "text": "#111827",
        "muted": "#6B7280",
        "bg": "#F7FCFA",
        "card": "#FFFFFF",
        "border": "#CFE8DD",
    },
    "Professional Gray": {
        "primary": "#374151",
        "secondary": "#111827",
        "accent": "#F3F4F6",
        "text": "#111827",
        "muted": "#6B7280",
        "bg": "#FAFAFA",
        "card": "#FFFFFF",
        "border": "#D1D5DB",
    },
    "Bordeaux": {
        "primary": "#9F1239",
        "secondary": "#4C0519",
        "accent": "#FFE4E6",
        "text": "#111827",
        "muted": "#6B7280",
        "bg": "#FFF8F9",
        "card": "#FFFFFF",
        "border": "#FBCFE8",
    },
}